import pyautogui # pip install pyautogui
import keyboard as k # pip install keyboard
import time
# say --> x: 0334 y: 0430 or 71, 318
time.sleep(3)
pyautogui.moveTo(334, 430, duration = 1.5) 

while True:
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("Please donate")
    k.press_and_release("enter")
    time.sleep(2.6)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    time.sleep(3.3)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    time.sleep(3.3)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("donate me to make me happy")
    k.press_and_release("enter")
    time.sleep(2.6)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    time.sleep(3.4)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    time.sleep(3.3)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("plsssssssss")
    k.press_and_release("enter")
    time.sleep(2.6)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
    time.sleep(3.3)
    pyautogui.dragTo(334, 430, duration=0.2, button="left")
    k.write("/e 3")
    k.press_and_release("enter")
